# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:vendasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console do H2 no navegador para ver as tabelas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra os comandos SQL que o Spring faz no terminal (ótimo para a apresentação)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Atualiza a estrutura do banco automaticamente
spring.jpa.hibernate.ddl-auto=update

# Configurações do Springdoc OpenAPI (Swagger UI)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html